### ISSUE TITLE
添加IE旧版本的Shim感觉没什么必要吧

### ISSUE THREAD

**Issue by jctang1202** [meislzhua/LiXiaBanHaiYouDuoJiu#11]
f6864632314d51aa93e3f870d7c09c79161289a2

**Comment by meislzhua** [comment]
我刚刚才看到,其实我之前也想过说, 尽量不要写太前卫的代码的,之前写过一次,结果手机,IE全部不行...
所以我想说尽量写兼容的代码.....
然而这个 `getElementsByClassName`就真有点过了
之后还要讨论一下兼容性究竟要去到哪里
