### ISSUE TITLE
command line 命令行工具

### ISSUE THREAD

**Issue by meislzhua** [meislzhua/LiXiaBanHaiYouDuoJiu#13]
实现 一个命令行工具 ,可以在js 自定义命令
第一个命令: 设置下班时间

ps:命令记得在 readme写好,代码写注释哦哦哦哦

**Comment by jctang1202** [comment]
反人类。

**Comment by meislzhua** [comment]
哈哈哈,这个只是辅助

**Comment by meislzhua** [comment]
这个需要在完成 [设置功能](https://github.com/meislzhua/LiXiaBanHaiYouDuoJiu/issues/8) 之后,再写
