### ISSUE TITLE
使 gulp 成为不是开发必备的

### ISSUE THREAD

**Issue by meislzhua** [meislzhua/LiXiaBanHaiYouDuoJiu#17]
现在需要gulp,才可以正常开发,对于没有gulp的环境的,根本没法进行开发或者测试

所以是否需要使gulp不是开发必备的?

**Comment by jctang1202** [comment]
开心就好。。。逃。。。/羊驼

**Comment by meislzhua** [comment]
但是要注意,不能让影响gulp的正常使用

**Comment by ONEWateR** [comment]
没必要 /羊驼
npm install 后就行了

**Comment by meislzhua** [comment]
这个考虑是因为并不是所有人都会有node的环境
开发是否一定需要node环境才可以开发呢
我个人觉得，node并不是开发html必要的因素→_→

**Comment by jctang1202** [comment]
公司PHP业务负责人：不会Node的前端就是一切图的。。 。逃。。。/囧

**Comment by meislzhua** [comment]
github好智能
